# -*- coding: utf-8 -*-
"""create_submission.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vtce_ecUDa7_B4x04_-tPglgTqpjIRKD
"""

import pandas as pd

def create_submission(df):

    submission = df[
        ["source1_entity_id",
         "matched_entity_ids"]
    ]

    submission.to_csv(
        "submission.csv",
        index=False
    )

    return submission