# -*- coding: utf-8 -*-
"""lightgbm_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16u9M_GE1_bfVl8izzLVAx9fV6PSdcv0H
"""

from lightgbm import LGBMClassifier

def get_model():

    return LGBMClassifier(
        n_estimators=300,
        learning_rate=0.05,
        random_state=42
    )