# -*- coding: utf-8 -*-
"""logistic_regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16u9M_GE1_bfVl8izzLVAx9fV6PSdcv0H
"""

from sklearn.linear_model import LogisticRegression

def get_model():

    return LogisticRegression(
        max_iter=1000,
        random_state=42
    )