# -*- coding: utf-8 -*-
"""random_forest

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16u9M_GE1_bfVl8izzLVAx9fV6PSdcv0H
"""

from sklearn.ensemble import RandomForestClassifier

def get_model():

    return RandomForestClassifier(
        n_estimators=200,
        random_state=42
    )