# -*- coding: utf-8 -*-
"""train

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16u9M_GE1_bfVl8izzLVAx9fV6PSdcv0H
"""

from sklearn.metrics import f1_score

def train_model(model, X_train, y_train):

    model.fit(X_train, y_train)

    return model


def evaluate_model(model, X_test, y_test):

    preds = model.predict(X_test)

    score = f1_score(y_test, preds)

    print("F1 Score:", score)

    return score