# -*- coding: utf-8 -*-
"""model_config

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16u9M_GE1_bfVl8izzLVAx9fV6PSdcv0H
"""

MODEL_PARAMS = {

    "random_forest": {
        "n_estimators": 200,
        "random_state": 42
    },

    "xgboost": {
        "n_estimators": 300,
        "max_depth": 6,
        "learning_rate": 0.05
    },

    "lightgbm": {
        "n_estimators": 300,
        "learning_rate": 0.05
    }
}
