# -*- coding: utf-8 -*-
"""predict

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16u9M_GE1_bfVl8izzLVAx9fV6PSdcv0H
"""

def predict_matches(model, X):

    predictions = model.predict(X)

    probabilities = model.predict_proba(X)[:, 1]

    return predictions, probabilities
